function shareRender(data, divId) {
    document.getElementById(divId).innerHTML 
    = '<div style="text-align: center">'
    + '<div class="mod_details lbor" style="width: 80%; border-width: 0 0 0 2px; margin-top: 6px; padding-left: 8px; border-color: #DDDDDD; border-style: none none none solid; display: inline-block;">'
    + '<div class="layout_s" style="margin-right: 8px; float: left;">'
    + '<a class="img_wrap group-picture" style="border-bottom: 0px; font-size: 0; line-height: 0; display: block; color: #26709A; text-decoration: none;"'
    + 'href="' + data.url + '"'
    + 'target="_blank">'
    + '<img src="' + data.picUrl + '"'
    + 'style="width: ' + data.width + 'px; height: ' + data.height + 'px; padding: 2px; border-color: #E0E0E0; border-style: solid; border-width: 1px;" class="bor3">'
    + '</a>'
    + '</div>'
    + '<div class="mod_brief" style="overflow: hidden; text-align: left;">'
    + '<h5 style="padding-top: 0px; margin-top: 0px; margin-bottom: 3px; font-size: 12px; width: 100%; font-weight: normal;">'
    + '<strong style="font-weight: bold;">'
    + '<a class="c_tx _share_title" style="border-bottom: 0px; color: #26709A;"'
    + 'href="' + data.url + '"'
    + 'target="_blank">' + data.title + '</a>'
    + '</strong>'
    + '</h5>'
    + '<p style="margin: 0 0 0 0; font-size: 12px; display: block; /*margin-block-start: 1em; margin-block-end: 1em;*/ margin-inline-start: 0px; margin-inline-end: 0px;">'
    + data.brief + '</p>'
    + '<p class="c_tx3 comming" style="margin: 0 0 0 0; font-size: 12px; margin-top: 3px; color: #9B9B9B;">'
    + '来自：'
    + '<a title="' + data.source + '"'
    + 'href="' + data.url + '"'
    + 'target="_blank" class="c_tx3 mgrm" style="border-bottom: 0px; margin-right: 10px; color: #9B9B9B;">' + data.source + '</a>'
    + '</p>'
    + '</div></div></div>';
}